config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :amounts
  resources :recipes
  resources :steps, only: [:new]
  resources :ingredients
  resources :categories
  root "home#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :ingredients
  has_many :steps, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :steps
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit new_step update destroy ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
    3.times do |i|
      @recipe.steps.build(number: i)
    end
  end

  def edit
  end

  def new_step
    @new_step_number = @recipe.steps.count
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipe_url(@recipe), notice: "Recipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe.steps.each(&:destroy!)
    @recipe.update!(recipe_params)
    redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated."
  end

  def destroy
    @recipe.destroy

    redirect_to recipes_url, notice: "Recipe was successfully destroyed."
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :steps, :description, steps_attributes: [:step, :notes, :number])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div>
  <%= form_with(model: recipe) do |form| %>
    <% if recipe.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset class="flex border-bottom-2 border-style-groove">
      <legend class="fs-8 border-bottom-2 border-style-groove">
        Recipe details:
      </legend>

      <div class="flex-grow-1 mt-1 mb-1">
        <label for="recipe_name">Name:</label>
        <textarea id="recipe_name" required="required" rows="2" name="recipe[name]"
          ><%= @recipe.name %></textarea>
      </div>

      <div class="flex-grow-2 mt-1 mb-1 ml-1">
        <label for="recipe_description">Description:</label>
        <textarea id="recipe_description" required="required" rows="2" name="recipe[description]"
          ><%= @recipe.description %></textarea>
      </div>
    </fieldset>

    <fieldset>
      <legend class="fs-8 border-bottom-2 border-style-groove">
        Recipe steps:
      </legend>

      <ol class="mt-1">
        <% num_steps = @recipe.steps.count %>
        <% @recipe.steps.order(:number).each_with_index do |step, ctr| %>
          <li data-controller="step-form--edit" class="step-list-item">
            <div class="flex">
              <div class="flex-grow-1 mr-1">
                <label for="recipe_steps_attributes_<%= ctr %>_step"
                    >Step <%= step.number %>:</label>
                <textarea rows="1" name="recipe[steps_attributes][<%= ctr %>][step]"
                                  id="recipe_steps_attributes_<%= ctr %>_step"
                    ><%= step.step %></textarea>
              </div>  

              <div class="flex-grow-1">
                <label for="recipe_steps_attributes_<%= ctr %>_notes"
                    >Notes:</label>
                <textarea
                      rows="1"
                      name="recipe[steps_attributes][<%= ctr %>][notes]"
                      id="recipe_steps_attributes_<%= ctr %>_notes"
                  ><%= step.notes %></textarea>
              </div>

              <div class="flex flex-col justify-around">
                <button
                    type="button"
                    title="Remove step"
                    class="remove-step-button mt-4 <%= (ctr + 1) == num_steps ? '' : 'display-none' %>"
                    data-action="click->step-form--edit#removeStep">
                  <%= render partial: "layouts/heroicons/trash", locals: { css_class: "w-6 h-6" } %>
                </button>
              </div>

              <input
                  autocomplete="off"
                  type="hidden" value="<%= step.number %>"
                  name="recipe[steps_attributes][<%= ctr %>][number]"
                  id="recipe_steps_attributes_<%= ctr %>_number" />
            </div>
          </li>
        <% end %>

        <%= turbo_frame_tag("new_step") do %>
          <%= link_to "New step", new_step_path %>
        <% end %>
      </ol>
    </fieldset>

    <div class="mt-2 mb-2">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1 class="fs-12 border-bottom-2 border-black border-style-groove text-align-center">
  Editing recipe <%= @recipe.id %>
</h1>

<%= render "form", recipe: @recipe %>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="fs-8 border-bottom-2 border-black border-style-groove">Recipes</h1>

<div id="recipes">
  <ul class="m-4">
    <% @recipes.each do |recipe| %>
      <li id="<%= dom_id recipe %>" class="list-inside list-circle">
        <%= link_to recipe.name, recipe %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New recipe", new_recipe_path %>

<%= link_to "Home", root_path %>

app/views/recipes/new.html.erb
<h1 class="fs-12 border-bottom-2 border-style-groove text-align-center">
  New recipe
</h1>

<%= render "form", recipe: @recipe %>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="fs-10 border-bottom-2 border-black border-style-groove mb-1">
  <%= @recipe.name %>
</h1>

<p class="mt-2 mb-1">
  <%= @recipe.description %>
</p>

<h2 class="fs-8 pr-2">
  Steps:
</h2>

<ol class="">
  <% @recipe.steps.each do |step| %>
    <li class="list-inside list-decimal">
      <%= step.step %>
      <% if step.notes %>
        <p class="ml-8">
          <%= step.notes %>
        </p>
      <% end %>
    </li>
  <% end %>
</ol>

<div class="mt-4">
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>