config/routes.rb
Rails.application.routes.draw do
  resources :units
  resources :amounts
  resources :recipes
  resources :steps, only: [:new]
  resources :ingredients
  resources :categories
  root "home#index"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :category, required: false
  has_and_belongs_to_many :recipes
  has_one :amount
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)

    if @ingredient.save
      redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created."
      render :show, status: :created, location: @ingredient
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @ingredient.destroy

    respond_to do |format|
      redirect_to ingredients_url, notice: "Ingredient was successfully destroyed."
    end
  end

  private
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name, :countable, :volumeable, :weighable, :excess, :category_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name:", style: "display: block" %>
    <%= form.text_field :name, required: true %>
  </div>

  <div>
    <%= form.label :type, "Type:" %>
    <%= select_tag :type,
        options_for_select([ "Count", "Weight", "Volume", "Excess" ]),
        prompt: "Select a measurement type:",
        title: "Select a measurement type:",
        required: true %>
  </div>

  <div class="mt-4">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p>
    <strong>Name:</strong>
    <%= ingredient.name %>
  </p>

  <p>
    <strong>Countable:</strong>
    <%= ingredient.countable %>
  </p>

  <p>
    <strong>Volumeable:</strong>
    <%= ingredient.volumeable %>
  </p>

  <p>
    <strong>Weighable:</strong>
    <%= ingredient.weighable %>
  </p>

  <p>
    <strong>Excess:</strong>
    <%= ingredient.excess %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= ingredient.category_id %>
  </p>

</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render "form", ingredient: @ingredient %>

<br>

<div>
  <%= link_to "Show this ingredient", @ingredient %> |
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="fs-8 border-bottom-2 border-black border-style-groove">Ingredients</h1>

<div id="ingredients">
  <ul class="m-4">
    <% @ingredients.each do |ingredient| %>
      <li id="<%= dom_id ingredient %>"  class="list-inside list-circle">
        <%= link_to ingredient.name, ingredient %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

<%= link_to "Home", root_path %>

app/views/ingredients/new.html.erb
<h1 class="fs-12 border-bottom-2 border-style-groove text-align-center">
  New ingredient
</h1>

<%= render "form", ingredient: @ingredient %>

<div>
  <%= link_to "Back to ingredients", ingredients_path %>
</div>

app/views/ingredients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>